insert_scene:
  description: Apply a scene to lights
  fields:
    entity_id:
      description: entity_id of scene to apply
      example: "scene.name_of_scene"
    id:
      description: Unique identifier of layer
      example: "my_layer_name"
    priority:
      description: Layer priority of scene (Higher the more visible)
      example: "0"
    clear_layer:
      description: Clears all other entity states from layer before applying when true.
      example: "true"

insert_state:
  description: Set entity state at specified layer.
  fields:
    entity_id:
      description: entity_id of entity or group
      example: "domain.name_of_entity"
    priority:
      description: Layer priority
      example: "0"
    id:
      description: Unique identifier of layer
      example: "my_layer_name"
    state:
      description: Desired entity state
      example: "on"
    attributes:
      description: State Attributes
    clear_layer:
      description: Clears all other entity states from layer before applying when true.
      example: "true"

remove_layer:
  description: Remove layer or scene from all lights, a specified group, or a specified light.
  fields:
    entity_id:
      description: entity_id of light or group. When no entity is specified, layer will be removed from all lights.
      example: "light.name_of_light"
    id:
      description: Layer ID or entity id of scene to be removed.
      example: "my_layer_name"

refresh_all:
  description: Refresh all managed entities to their current state.
