activate_layer:
  description: Activate a layer with optional state attributes.
  target:
    entity:
      domain: layer
  fields:
    brightness:
      description: Optional brightness value.
      selector:
        number:
          min: 0
          max: 255
          mode: slider
    color_temp:
      description: Optional color temperature in mireds.
      selector:
        number:
          min: 153
          max: 500
          mode: box
    rgb_color:
      description: Optional RGB color value.
      selector:
        color_rgb:
    transition:
      description: Transition time in seconds.
      selector:
        number:
          min: 0
          max: 60
          mode: box
    source:
      description: Source of this state.
      selector:
        text:
    force:
      description: Force this layer regardless of priority.
      selector:
        boolean:
    locked:
      description: Prevent further changes to this layer.
      selector:
        boolean:

deactivate_layer:
  description: Deactivate a layer.
  target:
    entity:
      domain: layer

update_layer:
  description: Update attributes of a layer without changing activation.
  target:
    entity:
      domain: layer
  fields:
    brightness:
      description: Optional brightness value.
      selector:
        number:
          min: 0
          max: 255
          mode: slider
    color_temp:
      description: Optional color temperature in mireds.
      selector:
        number:
          min: 153
          max: 500
          mode: box
    rgb_color:
      description: Optional RGB color value.
      selector:
        color_rgb:
    transition:
      description: Transition time in seconds.
      selector:
        number:
          min: 0
          max: 60
          mode: box
    source:
      description: Source of this state.
      selector:
        text:
    force:
      description: Force this layer regardless of priority.
      selector:
        boolean:
    locked:
      description: Prevent further changes to this layer.
      selector:
        boolean:
