insert_scene:
  description: Apply a scene to lights
  fields:
    entity_id:
      description: entity_id of scene to apply
      example: "scene.name_of_scene"
    priority:
      description: Layer priority of scene (Higher the more visible)
      example: "0"

remove_scene:
  description: Remomve scene from light layers
  fields:
    entity_id:
      description: entity_id of scene to remove
      example: "scene.name_of_scene"

insert_state:
  description: Set light state at specified layer.
  fields:
    entity_id:
      description: entity_id of light
      example: "light.name_of_light"
    priority:
      description: Layer priority
      example: "0"
    id:
      description: Unique identifier of layer
      example: "my_layer_name"
    attributes:
      description: State Attributes

remove_state:
  description: Remove state from layers.
  fields:
    entity_id:
      description: entity_id of light
      example: "light.name_of_light"
    id:
      description: Unique identifier of layer
      example: "my_layer_name"